// International address helpers — country list, state/province lookups,
// postal-code formats, phone hints. Used by the customer-facing order form so
// the inputs match each country's real conventions instead of US-only defaults.

export interface Country {
  code: string
  name: string
  postalLabel: string
  postalPlaceholder: string
  postalPattern?: RegExp
  statesRequired: boolean
  stateLabel: string
  phonePrefix: string
  phonePlaceholder: string
}

// Countries we currently ship to / accept PayPal payment from.
// Ordered roughly by current order volume + major English-speaking markets first.
export const COUNTRIES: Country[] = [
  {
    code: 'US',
    name: 'United States',
    postalLabel: 'ZIP Code',
    postalPlaceholder: '10001',
    postalPattern: /^\d{5}(-\d{4})?$/,
    statesRequired: true,
    stateLabel: 'State',
    phonePrefix: '+1',
    phonePlaceholder: '+1 (555) 000-0000',
  },
  {
    code: 'CA',
    name: 'Canada',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'K1A 0B1',
    postalPattern: /^[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d$/,
    statesRequired: true,
    stateLabel: 'Province',
    phonePrefix: '+1',
    phonePlaceholder: '+1 (416) 555-0000',
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    postalLabel: 'Postcode',
    postalPlaceholder: 'SW1A 1AA',
    postalPattern: /^[A-Za-z]{1,2}\d[A-Za-z\d]?\s?\d[A-Za-z]{2}$/,
    statesRequired: false,
    stateLabel: 'County',
    phonePrefix: '+44',
    phonePlaceholder: '+44 20 7946 0000',
  },
  {
    code: 'AU',
    name: 'Australia',
    postalLabel: 'Postcode',
    postalPlaceholder: '2000',
    postalPattern: /^\d{4}$/,
    statesRequired: true,
    stateLabel: 'State',
    phonePrefix: '+61',
    phonePlaceholder: '+61 2 9374 4000',
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    postalLabel: 'Postcode',
    postalPlaceholder: '1010',
    postalPattern: /^\d{4}$/,
    statesRequired: false,
    stateLabel: 'Region',
    phonePrefix: '+64',
    phonePlaceholder: '+64 9 123 4567',
  },
  {
    code: 'DE',
    name: 'Germany',
    postalLabel: 'Postleitzahl',
    postalPlaceholder: '10115',
    postalPattern: /^\d{5}$/,
    statesRequired: false,
    stateLabel: 'State',
    phonePrefix: '+49',
    phonePlaceholder: '+49 30 12345678',
  },
  {
    code: 'FR',
    name: 'France',
    postalLabel: 'Code Postal',
    postalPlaceholder: '75001',
    postalPattern: /^\d{5}$/,
    statesRequired: false,
    stateLabel: 'Region',
    phonePrefix: '+33',
    phonePlaceholder: '+33 1 23 45 67 89',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    postalLabel: 'Postcode',
    postalPlaceholder: '1011 AB',
    postalPattern: /^\d{4}\s?[A-Za-z]{2}$/,
    statesRequired: false,
    stateLabel: 'Province',
    phonePrefix: '+31',
    phonePlaceholder: '+31 20 123 4567',
  },
  {
    code: 'IT',
    name: 'Italy',
    postalLabel: 'CAP',
    postalPlaceholder: '00100',
    postalPattern: /^\d{5}$/,
    statesRequired: false,
    stateLabel: 'Province',
    phonePrefix: '+39',
    phonePlaceholder: '+39 06 12345678',
  },
  {
    code: 'ES',
    name: 'Spain',
    postalLabel: 'Código Postal',
    postalPlaceholder: '28001',
    postalPattern: /^\d{5}$/,
    statesRequired: false,
    stateLabel: 'Province',
    phonePrefix: '+34',
    phonePlaceholder: '+34 91 123 45 67',
  },
  {
    code: 'IE',
    name: 'Ireland',
    postalLabel: 'Eircode',
    postalPlaceholder: 'D02 X285',
    statesRequired: false,
    stateLabel: 'County',
    phonePrefix: '+353',
    phonePlaceholder: '+353 1 234 5678',
  },
  {
    code: 'CH',
    name: 'Switzerland',
    postalLabel: 'PLZ',
    postalPlaceholder: '8001',
    postalPattern: /^\d{4}$/,
    statesRequired: false,
    stateLabel: 'Canton',
    phonePrefix: '+41',
    phonePlaceholder: '+41 44 123 45 67',
  },
  {
    code: 'AT',
    name: 'Austria',
    postalLabel: 'PLZ',
    postalPlaceholder: '1010',
    postalPattern: /^\d{4}$/,
    statesRequired: false,
    stateLabel: 'State',
    phonePrefix: '+43',
    phonePlaceholder: '+43 1 123 4567',
  },
  {
    code: 'BE',
    name: 'Belgium',
    postalLabel: 'Postcode',
    postalPlaceholder: '1000',
    postalPattern: /^\d{4}$/,
    statesRequired: false,
    stateLabel: 'Province',
    phonePrefix: '+32',
    phonePlaceholder: '+32 2 123 45 67',
  },
  {
    code: 'SE',
    name: 'Sweden',
    postalLabel: 'Postnummer',
    postalPlaceholder: '111 22',
    postalPattern: /^\d{3}\s?\d{2}$/,
    statesRequired: false,
    stateLabel: 'County',
    phonePrefix: '+46',
    phonePlaceholder: '+46 8 123 456 78',
  },
  {
    code: 'NO',
    name: 'Norway',
    postalLabel: 'Postnummer',
    postalPlaceholder: '0150',
    postalPattern: /^\d{4}$/,
    statesRequired: false,
    stateLabel: 'County',
    phonePrefix: '+47',
    phonePlaceholder: '+47 22 12 34 56',
  },
  {
    code: 'DK',
    name: 'Denmark',
    postalLabel: 'Postnummer',
    postalPlaceholder: '1050',
    postalPattern: /^\d{4}$/,
    statesRequired: false,
    stateLabel: 'Region',
    phonePrefix: '+45',
    phonePlaceholder: '+45 32 12 34 56',
  },
  {
    code: 'FI',
    name: 'Finland',
    postalLabel: 'Postinumero',
    postalPlaceholder: '00100',
    postalPattern: /^\d{5}$/,
    statesRequired: false,
    stateLabel: 'Region',
    phonePrefix: '+358',
    phonePlaceholder: '+358 9 123 4567',
  },
  {
    code: 'JP',
    name: 'Japan',
    postalLabel: 'Postal Code',
    postalPlaceholder: '100-0001',
    postalPattern: /^\d{3}-?\d{4}$/,
    statesRequired: false,
    stateLabel: 'Prefecture',
    phonePrefix: '+81',
    phonePlaceholder: '+81 3-1234-5678',
  },
  {
    code: 'KR',
    name: 'South Korea',
    postalLabel: 'Postal Code',
    postalPlaceholder: '06000',
    postalPattern: /^\d{5}$/,
    statesRequired: false,
    stateLabel: 'Province',
    phonePrefix: '+82',
    phonePlaceholder: '+82 2-1234-5678',
  },
  {
    code: 'SG',
    name: 'Singapore',
    postalLabel: 'Postal Code',
    postalPlaceholder: '238823',
    postalPattern: /^\d{6}$/,
    statesRequired: false,
    stateLabel: 'Region',
    phonePrefix: '+65',
    phonePlaceholder: '+65 6123 4567',
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    postalLabel: 'Postal Code (optional)',
    postalPlaceholder: '999077',
    statesRequired: false,
    stateLabel: 'District',
    phonePrefix: '+852',
    phonePlaceholder: '+852 1234 5678',
  },
  {
    code: 'TW',
    name: 'Taiwan',
    postalLabel: 'Postal Code',
    postalPlaceholder: '100',
    postalPattern: /^\d{3}(\d{2,3})?$/,
    statesRequired: false,
    stateLabel: 'County',
    phonePrefix: '+886',
    phonePlaceholder: '+886 2 1234 5678',
  },
  {
    code: 'MY',
    name: 'Malaysia',
    postalLabel: 'Postal Code',
    postalPlaceholder: '50450',
    postalPattern: /^\d{5}$/,
    statesRequired: false,
    stateLabel: 'State',
    phonePrefix: '+60',
    phonePlaceholder: '+60 3-1234 5678',
  },
  {
    code: 'TH',
    name: 'Thailand',
    postalLabel: 'Postal Code',
    postalPlaceholder: '10110',
    postalPattern: /^\d{5}$/,
    statesRequired: false,
    stateLabel: 'Province',
    phonePrefix: '+66',
    phonePlaceholder: '+66 2 123 4567',
  },
  {
    code: 'IN',
    name: 'India',
    postalLabel: 'PIN Code',
    postalPlaceholder: '110001',
    postalPattern: /^\d{6}$/,
    statesRequired: true,
    stateLabel: 'State',
    phonePrefix: '+91',
    phonePlaceholder: '+91 98765 43210',
  },
  {
    code: 'MX',
    name: 'Mexico',
    postalLabel: 'Código Postal',
    postalPlaceholder: '01000',
    postalPattern: /^\d{5}$/,
    statesRequired: true,
    stateLabel: 'State',
    phonePrefix: '+52',
    phonePlaceholder: '+52 55 1234 5678',
  },
  {
    code: 'BR',
    name: 'Brazil',
    postalLabel: 'CEP',
    postalPlaceholder: '01310-100',
    postalPattern: /^\d{5}-?\d{3}$/,
    statesRequired: true,
    stateLabel: 'State',
    phonePrefix: '+55',
    phonePlaceholder: '+55 11 91234 5678',
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    postalLabel: 'Postal Code (optional)',
    postalPlaceholder: '00000',
    statesRequired: false,
    stateLabel: 'Emirate',
    phonePrefix: '+971',
    phonePlaceholder: '+971 4 123 4567',
  },
  {
    code: 'IL',
    name: 'Israel',
    postalLabel: 'Postal Code',
    postalPlaceholder: '6100000',
    postalPattern: /^\d{5}(\d{2})?$/,
    statesRequired: false,
    stateLabel: 'District',
    phonePrefix: '+972',
    phonePlaceholder: '+972 3 123 4567',
  },
]

// Sub-region dropdowns for countries where statesRequired === true.
// (Other countries use a free-text input so we don't have to maintain every list.)
export const STATES_BY_COUNTRY: Record<string, { code: string; name: string }[]> = {
  US: [
    { code: 'AL', name: 'Alabama' }, { code: 'AK', name: 'Alaska' },
    { code: 'AZ', name: 'Arizona' }, { code: 'AR', name: 'Arkansas' },
    { code: 'CA', name: 'California' }, { code: 'CO', name: 'Colorado' },
    { code: 'CT', name: 'Connecticut' }, { code: 'DE', name: 'Delaware' },
    { code: 'DC', name: 'District of Columbia' }, { code: 'FL', name: 'Florida' },
    { code: 'GA', name: 'Georgia' }, { code: 'HI', name: 'Hawaii' },
    { code: 'ID', name: 'Idaho' }, { code: 'IL', name: 'Illinois' },
    { code: 'IN', name: 'Indiana' }, { code: 'IA', name: 'Iowa' },
    { code: 'KS', name: 'Kansas' }, { code: 'KY', name: 'Kentucky' },
    { code: 'LA', name: 'Louisiana' }, { code: 'ME', name: 'Maine' },
    { code: 'MD', name: 'Maryland' }, { code: 'MA', name: 'Massachusetts' },
    { code: 'MI', name: 'Michigan' }, { code: 'MN', name: 'Minnesota' },
    { code: 'MS', name: 'Mississippi' }, { code: 'MO', name: 'Missouri' },
    { code: 'MT', name: 'Montana' }, { code: 'NE', name: 'Nebraska' },
    { code: 'NV', name: 'Nevada' }, { code: 'NH', name: 'New Hampshire' },
    { code: 'NJ', name: 'New Jersey' }, { code: 'NM', name: 'New Mexico' },
    { code: 'NY', name: 'New York' }, { code: 'NC', name: 'North Carolina' },
    { code: 'ND', name: 'North Dakota' }, { code: 'OH', name: 'Ohio' },
    { code: 'OK', name: 'Oklahoma' }, { code: 'OR', name: 'Oregon' },
    { code: 'PA', name: 'Pennsylvania' }, { code: 'PR', name: 'Puerto Rico' },
    { code: 'RI', name: 'Rhode Island' }, { code: 'SC', name: 'South Carolina' },
    { code: 'SD', name: 'South Dakota' }, { code: 'TN', name: 'Tennessee' },
    { code: 'TX', name: 'Texas' }, { code: 'UT', name: 'Utah' },
    { code: 'VT', name: 'Vermont' }, { code: 'VA', name: 'Virginia' },
    { code: 'WA', name: 'Washington' }, { code: 'WV', name: 'West Virginia' },
    { code: 'WI', name: 'Wisconsin' }, { code: 'WY', name: 'Wyoming' },
  ],
  CA: [
    { code: 'AB', name: 'Alberta' }, { code: 'BC', name: 'British Columbia' },
    { code: 'MB', name: 'Manitoba' }, { code: 'NB', name: 'New Brunswick' },
    { code: 'NL', name: 'Newfoundland and Labrador' }, { code: 'NS', name: 'Nova Scotia' },
    { code: 'NT', name: 'Northwest Territories' }, { code: 'NU', name: 'Nunavut' },
    { code: 'ON', name: 'Ontario' }, { code: 'PE', name: 'Prince Edward Island' },
    { code: 'QC', name: 'Quebec' }, { code: 'SK', name: 'Saskatchewan' },
    { code: 'YT', name: 'Yukon' },
  ],
  AU: [
    { code: 'ACT', name: 'Australian Capital Territory' },
    { code: 'NSW', name: 'New South Wales' }, { code: 'NT', name: 'Northern Territory' },
    { code: 'QLD', name: 'Queensland' }, { code: 'SA', name: 'South Australia' },
    { code: 'TAS', name: 'Tasmania' }, { code: 'VIC', name: 'Victoria' },
    { code: 'WA', name: 'Western Australia' },
  ],
  IN: [
    { code: 'AN', name: 'Andaman and Nicobar Islands' }, { code: 'AP', name: 'Andhra Pradesh' },
    { code: 'AR', name: 'Arunachal Pradesh' }, { code: 'AS', name: 'Assam' },
    { code: 'BR', name: 'Bihar' }, { code: 'CH', name: 'Chandigarh' },
    { code: 'CT', name: 'Chhattisgarh' }, { code: 'DL', name: 'Delhi' },
    { code: 'GA', name: 'Goa' }, { code: 'GJ', name: 'Gujarat' },
    { code: 'HR', name: 'Haryana' }, { code: 'HP', name: 'Himachal Pradesh' },
    { code: 'JK', name: 'Jammu and Kashmir' }, { code: 'JH', name: 'Jharkhand' },
    { code: 'KA', name: 'Karnataka' }, { code: 'KL', name: 'Kerala' },
    { code: 'LA', name: 'Ladakh' }, { code: 'MP', name: 'Madhya Pradesh' },
    { code: 'MH', name: 'Maharashtra' }, { code: 'MN', name: 'Manipur' },
    { code: 'ML', name: 'Meghalaya' }, { code: 'MZ', name: 'Mizoram' },
    { code: 'NL', name: 'Nagaland' }, { code: 'OR', name: 'Odisha' },
    { code: 'PY', name: 'Puducherry' }, { code: 'PB', name: 'Punjab' },
    { code: 'RJ', name: 'Rajasthan' }, { code: 'SK', name: 'Sikkim' },
    { code: 'TN', name: 'Tamil Nadu' }, { code: 'TG', name: 'Telangana' },
    { code: 'TR', name: 'Tripura' }, { code: 'UP', name: 'Uttar Pradesh' },
    { code: 'UT', name: 'Uttarakhand' }, { code: 'WB', name: 'West Bengal' },
  ],
  MX: [
    { code: 'AGU', name: 'Aguascalientes' }, { code: 'BCN', name: 'Baja California' },
    { code: 'BCS', name: 'Baja California Sur' }, { code: 'CAM', name: 'Campeche' },
    { code: 'CHP', name: 'Chiapas' }, { code: 'CHH', name: 'Chihuahua' },
    { code: 'CMX', name: 'Mexico City' }, { code: 'COA', name: 'Coahuila' },
    { code: 'COL', name: 'Colima' }, { code: 'DUR', name: 'Durango' },
    { code: 'GUA', name: 'Guanajuato' }, { code: 'GRO', name: 'Guerrero' },
    { code: 'HID', name: 'Hidalgo' }, { code: 'JAL', name: 'Jalisco' },
    { code: 'MEX', name: 'México State' }, { code: 'MIC', name: 'Michoacán' },
    { code: 'MOR', name: 'Morelos' }, { code: 'NAY', name: 'Nayarit' },
    { code: 'NLE', name: 'Nuevo León' }, { code: 'OAX', name: 'Oaxaca' },
    { code: 'PUE', name: 'Puebla' }, { code: 'QUE', name: 'Querétaro' },
    { code: 'ROO', name: 'Quintana Roo' }, { code: 'SLP', name: 'San Luis Potosí' },
    { code: 'SIN', name: 'Sinaloa' }, { code: 'SON', name: 'Sonora' },
    { code: 'TAB', name: 'Tabasco' }, { code: 'TAM', name: 'Tamaulipas' },
    { code: 'TLA', name: 'Tlaxcala' }, { code: 'VER', name: 'Veracruz' },
    { code: 'YUC', name: 'Yucatán' }, { code: 'ZAC', name: 'Zacatecas' },
  ],
  BR: [
    { code: 'AC', name: 'Acre' }, { code: 'AL', name: 'Alagoas' },
    { code: 'AP', name: 'Amapá' }, { code: 'AM', name: 'Amazonas' },
    { code: 'BA', name: 'Bahia' }, { code: 'CE', name: 'Ceará' },
    { code: 'DF', name: 'Federal District' }, { code: 'ES', name: 'Espírito Santo' },
    { code: 'GO', name: 'Goiás' }, { code: 'MA', name: 'Maranhão' },
    { code: 'MT', name: 'Mato Grosso' }, { code: 'MS', name: 'Mato Grosso do Sul' },
    { code: 'MG', name: 'Minas Gerais' }, { code: 'PA', name: 'Pará' },
    { code: 'PB', name: 'Paraíba' }, { code: 'PR', name: 'Paraná' },
    { code: 'PE', name: 'Pernambuco' }, { code: 'PI', name: 'Piauí' },
    { code: 'RJ', name: 'Rio de Janeiro' }, { code: 'RN', name: 'Rio Grande do Norte' },
    { code: 'RS', name: 'Rio Grande do Sul' }, { code: 'RO', name: 'Rondônia' },
    { code: 'RR', name: 'Roraima' }, { code: 'SC', name: 'Santa Catarina' },
    { code: 'SP', name: 'São Paulo' }, { code: 'SE', name: 'Sergipe' },
    { code: 'TO', name: 'Tocantins' },
  ],
}

export function getCountry(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code)
}

export function isPostalCodeValid(countryCode: string, postal: string): boolean {
  const country = getCountry(countryCode)
  if (!country) return true
  if (!country.postalPattern) return postal.trim().length > 0
  return country.postalPattern.test(postal.trim())
}
