// OMO-3684 · Procardcrafters Ad Studio — 인스타 피드 + 메타 광고 콘텐츠 단일 진실원천(SSOT).
// 뉴트리바이오비스(bioridge) 광고 스튜디오 패턴 참고: locked frame + variation, 컴플라이언스 게이트.
//
// 컴플라이언스(필수):
// - 고객 노출 카피는 영어(미국 B2C POD). 스튜디오 UI 라벨/주석은 한국어(회사 언어 규칙).
// - 가짜 후기/평점/근거불명 합산 stat 금지(OMO-2975). 검증가능한 운영 사실만.
// - 내부 수량 임계값 노출 금지, 전화번호 노출 금지 → 견적/콜백 CTA(OMO-2760).
// - 메타 광고 구조/지표는 전사 META_ADS 표준(OMO-3444): 신규=1캠페인-1광고세트-1광고,
//   1차 지표=CTR+ROI(대시보드 ROAS는 보조), 테스트 예산=CAC×3~5.
//
// ⚠️ 이미지는 현재 in-browser 렌더(그라데이션 배경 + CSS 카드 목업)로 "컨셉 프루프".
//    실사 제품촬영/AI 배경 합성은 키작업(이미지 파이프라인) 이후 자식 이슈에서 교체한다.

// OMO-3690 · 생성 이미지 매니페스트(IG-id → Supabase public URL). 생성 스크립트가 채움.
import GENERATED_IMAGES from './studio-generated.json'

export type CreativeRatio = '4:5' | '1:1' | '9:16'
export type CreativeFormat = 'single' | 'carousel' | 'cardnews'

// locked frame 배경 테마 (procard 브랜드: navy/blue/indigo + amber/gold 악센트)
export type ThemeKey =
  | 'goldFoil'
  | 'letterpress'
  | 'transparent'
  | 'pearl'
  | 'metallic'
  | 'navy'
  | 'studio'
  | 'kraft'
  | 'holographic'
  | 'wedding'
  | 'amber'
  | 'mono'

export interface CardNewsSlide {
  title: string
  text: string
}

export interface InstagramPost {
  id: string // IG-01 ...
  slug: string
  productSlug: string
  productLabel: string
  category: 'cards' | 'stickers' | 'marketing' | 'office' | 'brand'
  format: CreativeFormat
  ratio: CreativeRatio
  theme: ThemeKey
  headline: string // 화면 헤드라인(영어, 2줄 가능)
  subhead: string // 그 아래 한 줄
  caption: string // IG 캡션(첫 줄 훅)
  cta: string
  hashtags: string[] // # 제외
  visualDirection: string // 디자이너/이미지 파이프라인용 비주얼 가이드(한국어 허용)
  imageUrl?: string // OMO-3690: 실사/AI 프로덕션 이미지 URL(Supabase mkt-uploads procard/). 비면 CSS 컨셉 목업 폴백.
  slides?: CardNewsSlide[] // carousel/cardnews 전용
}

export type MetaObjective =
  | 'OUTCOME_TRAFFIC'
  | 'OUTCOME_SALES'
  | 'OUTCOME_LEADS'
  | 'OUTCOME_ENGAGEMENT'

export interface MetaAdSet {
  id: string // AD-01 ...
  campaign: string
  adsetName: string
  adName: string // 표준 네이밍: Procard_{platform}_{code}_v1
  objective: MetaObjective
  audience: string // 타겟 설명(미국)
  placements: string
  primaryText: string // 본문(영어)
  headline: string // 40자 이내 헤드라인(영어)
  description: string // 링크 설명(영어)
  ctaButton: 'Shop Now' | 'Get Offer' | 'Learn More' | 'Get Quote' | 'Sign Up'
  destination: string // 랜딩(상품/견적 페이지 슬러그)
  creativeRef: string // 연결된 IG-xx 크리에이티브
  primaryMetric: 'CTR + ROI'
  budgetRule: string // CAC×3~5 가이드
  structure: '1c-1a-1ad (test)' | '1c-1a-multiad (scale)'
}

// ---------------------------------------------------------------------------
// 인스타그램 포스팅 30종 (피드/카드뉴스/유즈케이스/브랜드)
// ---------------------------------------------------------------------------
const RAW_INSTAGRAM_POSTS: InstagramPost[] = [
  // --- A. 프리미엄 카드 히어로 (8) ---
  {
    id: 'IG-01',
    slug: 'gold-foil-hero',
    productSlug: 'premium-foil-cards',
    productLabel: 'Foil Business Cards',
    category: 'cards',
    format: 'single',
    ratio: '4:5',
    theme: 'goldFoil',
    headline: 'Gold that\nactually shines',
    subhead: 'Real metallic foil. Not printed gold.',
    caption: 'The difference is in the light. Real foil catches every angle — printed "gold" just sits flat. Hand one over and watch them look twice.',
    cta: 'Design your foil card',
    hashtags: ['businesscards', 'foilstamping', 'goldfoil', 'luxurystationery', 'branding', 'smallbusiness'],
    visualDirection: '딥 네이비 벨벳 배경, 45° 기울인 검정 카드에 금박 로고 클로즈업, 한쪽에서 들어오는 스폿 조명으로 foil specular 강조. 매크로 텍스처.',
  },
  {
    id: 'IG-02',
    slug: 'letterpress-impression',
    productSlug: 'letterpress-business-cards',
    productLabel: 'Letterpress Cards',
    category: 'cards',
    format: 'single',
    ratio: '4:5',
    theme: 'letterpress',
    headline: 'You can feel\nthe quality',
    subhead: 'Deep cotton-stock impression.',
    caption: 'Some cards you see. Letterpress you feel — a deep press into thick cotton stock that says "this brand cares about details."',
    cta: 'Try letterpress',
    hashtags: ['letterpress', 'businesscards', 'cottonpaper', 'designersgonnadesign', 'brandidentity', 'print'],
    visualDirection: '크림 코튼 카드 측면 매크로, 활자 눌린 깊이(deboss) 그림자 강조, 자연광 측광. 손끝이 텍스처를 만지는 컷 1장.',
  },
  {
    id: 'IG-03',
    slug: 'transparent-clear',
    productSlug: 'transparent-business-cards',
    productLabel: 'Transparent Cards',
    category: 'cards',
    format: 'single',
    ratio: '1:1',
    theme: 'transparent',
    headline: 'See-through.\nUnforgettable.',
    subhead: 'Frosted plastic that stands out in any wallet.',
    caption: 'Hand someone a clear card and it never ends up in the bin. Frosted plastic, sharp print, premium feel.',
    cta: 'Go transparent',
    hashtags: ['transparentcard', 'plasticcards', 'businesscards', 'standout', 'modernbranding', 'design'],
    visualDirection: '밝은 그라데이션 배경 위에 떠 있는 반투명 프로스트 카드, 뒤 배경이 비치는 효과, 가장자리 빛 굴절. 손에 들어 빛에 비추는 컷.',
  },
  {
    id: 'IG-04',
    slug: 'pearl-shimmer',
    productSlug: 'pearl-business-cards',
    productLabel: 'Pearl Cards',
    category: 'cards',
    format: 'single',
    ratio: '4:5',
    theme: 'pearl',
    headline: 'A subtle\npearl shimmer',
    subhead: 'Catches light without trying too hard.',
    caption: 'Understated, not boring. Pearlescent stock gives a soft shimmer that reads "premium" the second it\'s in hand.',
    cta: 'See pearl stock',
    hashtags: ['pearlcards', 'businesscards', 'luxurybranding', 'stationery', 'premiumprint', 'design'],
    visualDirection: '소프트 핑크-화이트 배경, 펄지 카드가 빛 따라 무지개빛 반사, 부드러운 회전 모션 한 컷. 미니멀.',
  },
  {
    id: 'IG-05',
    slug: 'metallic-edge',
    productSlug: 'metallic-business-cards',
    productLabel: 'Metallic Cards',
    category: 'cards',
    format: 'single',
    ratio: '1:1',
    theme: 'metallic',
    headline: 'Built like\na statement',
    subhead: 'Metallic stock with a cool, modern sheen.',
    caption: 'For brands that don\'t whisper. Metallic stock with a brushed sheen — looks engineered, feels expensive.',
    cta: 'Explore metallic',
    hashtags: ['metalliccards', 'businesscards', 'modernbranding', 'premium', 'designinspo', 'print'],
    visualDirection: '다크 그레이 배경, 브러시드 메탈릭 카드, 차가운 반사 하이라이트가 표면을 가로지름. 기하학적 그림자.',
  },
  {
    id: 'IG-06',
    slug: 'uv-spot-gloss',
    productSlug: 'uv-business-cards',
    productLabel: 'Spot UV Cards',
    category: 'cards',
    format: 'single',
    ratio: '4:5',
    theme: 'navy',
    headline: 'Matte black.\nGlossy logo.',
    subhead: 'Spot UV that pops only where it counts.',
    caption: 'The trick that makes designers smile: a matte card with glossy spot-UV detail. Same color, different finish — pure contrast.',
    cta: 'Add spot UV',
    hashtags: ['spotuv', 'businesscards', 'matteblack', 'graphicdesign', 'printdesign', 'branding'],
    visualDirection: '매트 블랙 카드 위 로고만 글로시 UV, 측광으로 글로시 영역만 반짝. 같은 검정 안의 매트 vs 글로스 대비 강조.',
  },
  {
    id: 'IG-07',
    slug: 'holographic-sticker-hero',
    productSlug: 'holographic-stickers',
    productLabel: 'Holographic Stickers',
    category: 'stickers',
    format: 'single',
    ratio: '1:1',
    theme: 'holographic',
    headline: 'Rainbow on\nrepeat',
    subhead: 'Holographic stickers that move with the light.',
    caption: 'Slap one on a laptop, a bottle, a package — holographic shimmer that shifts color as it moves. People will ask where you got them.',
    cta: 'Make holographic stickers',
    hashtags: ['holographicstickers', 'stickers', 'packaging', 'smallbusiness', 'brandstickers', 'etsyseller'],
    visualDirection: '밝은 배경 위 홀로그래픽 스티커 여러 장, 무지개 반사가 각도마다 다르게. 노트북/물병에 붙인 라이프스타일 컷.',
  },
  {
    id: 'IG-08',
    slug: 'die-cut-any-shape',
    productSlug: 'die-cut-stickers',
    productLabel: 'Die-Cut Stickers',
    category: 'stickers',
    format: 'single',
    ratio: '4:5',
    theme: 'studio',
    headline: 'Any shape\nyou can draw',
    subhead: 'Die-cut to your exact outline.',
    caption: 'Logo, mascot, lettering — if you can draw it, we can cut it. Clean die-cut edges, weatherproof finish.',
    cta: 'Cut your shape',
    hashtags: ['diecutstickers', 'stickers', 'customstickers', 'branding', 'smallbiz', 'packaging'],
    visualDirection: '파스텔 배경, 다양한 모양(별/말풍선/하트/로고) 다이컷 스티커 흩뿌림, 살짝 들린 모서리로 다이컷 강조.',
  },

  // --- B. 카드뉴스/교육 캐러셀 (8) ---
  {
    id: 'IG-09',
    slug: 'cardnews-cheap-mistakes',
    productSlug: 'business-cards',
    productLabel: 'Business Cards',
    category: 'cards',
    format: 'cardnews',
    ratio: '4:5',
    theme: 'mono',
    headline: '5 things that\nmake a card\nlook cheap',
    subhead: 'Swipe →',
    caption: 'Your card is a first impression in 90mm. Avoid these 5 and it instantly reads more premium. Which one are you guilty of?',
    cta: 'Fix yours',
    hashtags: ['businesscards', 'designtips', 'branding', 'smallbusinesstips', 'graphicdesign', 'printdesign'],
    visualDirection: '미니멀 모노 배경 카드뉴스 6장, 큰 숫자 + 한 줄 카피, 마지막 장 CTA. 일관된 그리드/타이포.',
    slides: [
      { title: '5 things that make a card look cheap', text: 'And the quick fix for each. Swipe →' },
      { title: '1. Thin paper', text: 'Flimsy stock feels disposable. Go 400gsm+ and people keep it.' },
      { title: '2. No finish', text: 'A flat print blends in. Matte, soft-touch or spot-UV adds instant value.' },
      { title: '3. Crowded layout', text: 'White space reads premium. Cut everything that isn\'t the name, role, and one contact.' },
      { title: '4. Low-res logo', text: 'Blurry edges = amateur. Use a vector file, not a screenshot.' },
      { title: '5. Default template look', text: 'Pick a finish + paper that match your brand. That\'s the whole game.' },
    ],
  },
  {
    id: 'IG-10',
    slug: 'cardnews-finishes',
    productSlug: 'premium-business-cards',
    productLabel: 'Premium Cards',
    category: 'cards',
    format: 'cardnews',
    ratio: '4:5',
    theme: 'navy',
    headline: 'Matte vs Gloss\nvs Soft-touch',
    subhead: 'Which finish is right for you? →',
    caption: 'Same design, three finishes, three completely different vibes. Here\'s how to choose.',
    cta: 'Compare finishes',
    hashtags: ['printfinishes', 'businesscards', 'designtips', 'branding', 'softtouch', 'matte'],
    visualDirection: '동일 카드 3종(매트/글로스/소프트터치) 나란히, 각 장에서 한 finish 클로즈업 + 짧은 설명. 비교 그리드.',
    slides: [
      { title: 'Matte vs Gloss vs Soft-touch', text: 'Pick the finish that matches your brand. Swipe →' },
      { title: 'Matte', text: 'No glare, easy to read, understated. The safe premium choice.' },
      { title: 'Gloss', text: 'Vivid colors, photo-friendly, energetic. Great for bold brands.' },
      { title: 'Soft-touch', text: 'Velvety feel, fingerprint-resistant, luxe. The one people comment on.' },
      { title: 'Still unsure?', text: 'Tell us your brand vibe and we\'ll recommend one. Free design help.' },
    ],
  },
  {
    id: 'IG-11',
    slug: 'cardnews-anatomy',
    productSlug: 'business-cards',
    productLabel: 'Business Cards',
    category: 'cards',
    format: 'cardnews',
    ratio: '4:5',
    theme: 'studio',
    headline: 'Anatomy of a\ncard people\nactually keep',
    subhead: 'Swipe →',
    caption: 'Most cards get tossed within a day. The ones that survive do these things. Steal this checklist.',
    cta: 'Build a keeper',
    hashtags: ['businesscards', 'branding', 'designtips', 'smallbusiness', 'marketingtips', 'print'],
    visualDirection: '카드 한 장을 분해하는 레이아웃(라인 콜아웃), 각 슬라이드가 한 요소 강조. 도식적.',
    slides: [
      { title: 'A card people keep', text: '6 details that stop your card from hitting the trash. Swipe →' },
      { title: 'A reason to flip it', text: 'A QR, an offer, a map — give the back a job.' },
      { title: 'One clear contact', text: 'Don\'t list five ways to reach you. Pick the one that converts.' },
      { title: 'A finish they touch', text: 'Texture makes people hold it longer. Holding = remembering.' },
      { title: 'Brand color, edge to edge', text: 'Painted/colored edges turn a card into a keepsake.' },
      { title: 'Want help?', text: 'Upload your logo — we\'ll lay it out for free before you pay.' },
    ],
  },
  {
    id: 'IG-12',
    slug: 'cardnews-design-4-steps',
    productSlug: 'business-cards',
    productLabel: 'Business Cards',
    category: 'cards',
    format: 'cardnews',
    ratio: '4:5',
    theme: 'amber',
    headline: 'Design a card\nin 4 steps',
    subhead: 'No designer needed →',
    caption: 'You don\'t need design software. Four steps from logo to door. Save this for your next order.',
    cta: 'Start step 1',
    hashtags: ['businesscards', 'diydesign', 'smallbusiness', 'branding', 'howto', 'print'],
    visualDirection: '1-2-3-4 스텝 카드뉴스, 큰 스텝 넘버 + 아이콘. 마지막 장 "upload → firm price" CTA.',
    slides: [
      { title: 'Design a card in 4 steps', text: 'From logo to your door. Swipe →' },
      { title: '1. Pick a stock', text: 'Standard, premium cotton, plastic, or metallic — set the feel first.' },
      { title: '2. Choose a finish', text: 'Foil, letterpress, spot-UV, or clean matte. One hero detail is enough.' },
      { title: '3. Upload your logo', text: 'Vector file ideal. We position it and send a proof.' },
      { title: '4. Approve & ship', text: 'Firm price before you pay. FedEx to your door worldwide.' },
    ],
  },
  {
    id: 'IG-13',
    slug: 'cardnews-paper-weights',
    productSlug: 'premium-business-cards',
    productLabel: 'Premium Cards',
    category: 'cards',
    format: 'cardnews',
    ratio: '4:5',
    theme: 'kraft',
    headline: 'Paper weight,\nexplained',
    subhead: '300 vs 400 vs 600gsm →',
    caption: 'Why does one card feel cheap and another feel like a credit card? It\'s mostly the gsm. Quick guide.',
    cta: 'Pick your weight',
    hashtags: ['paperweight', 'businesscards', 'printtips', 'stationery', 'designtips', 'branding'],
    visualDirection: '카드 두께 측면 매크로 3종 비교, gsm 라벨. 손으로 휘어보는 컷으로 강성 차이.',
    slides: [
      { title: 'Paper weight, explained', text: 'gsm = how thick & sturdy your card feels. Swipe →' },
      { title: '300gsm', text: 'Standard. Fine for everyday cards and flyers.' },
      { title: '400gsm', text: 'The sweet spot. Sturdy, premium, doesn\'t bend in a pocket.' },
      { title: '600gsm', text: 'Credit-card thick. Pair with painted edges for a true luxury feel.' },
      { title: 'Our default?', text: 'We lead with 400gsm+ so your card never feels flimsy.' },
    ],
  },
  {
    id: 'IG-14',
    slug: 'cardnews-foil-vs-letterpress',
    productSlug: 'premium-foil-cards',
    productLabel: 'Foil Cards',
    category: 'cards',
    format: 'cardnews',
    ratio: '4:5',
    theme: 'goldFoil',
    headline: 'Foil vs\nLetterpress vs\nEmboss',
    subhead: 'What\'s the difference? →',
    caption: 'Three "premium" finishes people mix up. Here\'s what each actually does — so you order the right one.',
    cta: 'See premium finishes',
    hashtags: ['foilstamping', 'letterpress', 'embossing', 'businesscards', 'printtips', 'luxuryprint'],
    visualDirection: '각 finish 매크로 1장씩(금박 반사 / 눌린 깊이 / 양각 솟음), 측광. 비교 카드뉴스.',
    slides: [
      { title: 'Foil vs Letterpress vs Emboss', text: 'Three premium finishes, three different effects. Swipe →' },
      { title: 'Foil', text: 'Metallic shine pressed onto the surface. Maximum "wow" in the light.' },
      { title: 'Letterpress', text: 'A deep press *into* the paper. You feel the impression.' },
      { title: 'Emboss', text: 'Raised *up* from the surface. Tactile, dimensional, classic.' },
      { title: 'Combine them', text: 'Foil + letterpress on cotton stock is the designer\'s favorite combo.' },
    ],
  },
  {
    id: 'IG-15',
    slug: 'cardnews-qr-dos-donts',
    productSlug: 'business-cards',
    productLabel: 'Business Cards',
    category: 'cards',
    format: 'cardnews',
    ratio: '4:5',
    theme: 'navy',
    headline: 'QR codes\non cards:\ndo\'s & don\'ts',
    subhead: 'Swipe →',
    caption: 'A QR turns a paper card into a link to everything. But a bad one just looks cluttered. Do it right.',
    cta: 'Add a QR',
    hashtags: ['qrcode', 'businesscards', 'marketingtips', 'smallbusiness', 'branding', 'designtips'],
    visualDirection: '카드 뒷면 QR 클로즈업, 스마트폰이 스캔하는 컷. do/don\'t 대비 슬라이드.',
    slides: [
      { title: 'QR codes on cards', text: 'The do\'s and don\'ts. Swipe →' },
      { title: 'DO link to one action', text: 'Booking page, portfolio, or vCard — not your whole website.' },
      { title: 'DO give it quiet space', text: 'A QR needs margin around it to scan. Don\'t crowd it.' },
      { title: 'DON\'T shrink it too small', text: 'Keep it scannable at arm\'s length. Test before you print.' },
      { title: 'DO put it on the back', text: 'Front for identity, back for the action. Clean and intentional.' },
    ],
  },
  {
    id: 'IG-16',
    slug: 'cardnews-sticker-guide',
    productSlug: 'stickers',
    productLabel: 'Stickers',
    category: 'stickers',
    format: 'cardnews',
    ratio: '1:1',
    theme: 'holographic',
    headline: 'Sticker shapes\n& finishes\nguide',
    subhead: 'Swipe →',
    caption: 'Die-cut, holographic, kraft, clear, eco — which sticker fits your brand? Save this before your next batch.',
    cta: 'Make stickers',
    hashtags: ['stickers', 'customstickers', 'smallbusiness', 'packaging', 'branding', 'etsy'],
    visualDirection: '스티커 종류별 1장씩 클로즈업(다이컷/홀로/크라프트/투명/에코), 라이프스타일 적용 컷 1장.',
    slides: [
      { title: 'Sticker shapes & finishes', text: 'Pick the right one for your brand. Swipe →' },
      { title: 'Die-cut', text: 'Cut to any outline. Best for logos and mascots.' },
      { title: 'Holographic', text: 'Rainbow shimmer. Premium packaging and laptop swag.' },
      { title: 'Kraft / Eco', text: 'Natural, recyclable look. Perfect for artisan brands.' },
      { title: 'Clear', text: 'Floats on glass and bottles. Looks like part of the product.' },
    ],
  },

  // --- C. 유즈케이스/페르소나 (8) ---
  {
    id: 'IG-17',
    slug: 'usecase-realtor',
    productSlug: 'premium-business-cards',
    productLabel: 'Premium Cards',
    category: 'cards',
    format: 'single',
    ratio: '4:5',
    theme: 'navy',
    headline: 'Your card is\nyour first\nshowing',
    subhead: 'Premium cards for real estate pros.',
    caption: 'Buyers judge fast. A heavy, premium card with a QR to your listings says "I close." Make every handoff count.',
    cta: 'Realtor cards',
    hashtags: ['realtor', 'realestate', 'realtorlife', 'businesscards', 'realestatemarketing', 'branding'],
    visualDirection: '깔끔한 부동산 톤(네이비/골드), 카드 + 집 열쇠 + QR. 프로페셔널 데스크 플랫레이.',
  },
  {
    id: 'IG-18',
    slug: 'usecase-cafe',
    productSlug: 'business-cards',
    productLabel: 'Loyalty + Business Cards',
    category: 'cards',
    format: 'single',
    ratio: '1:1',
    theme: 'kraft',
    headline: 'Buy 9, get 1.\nPrinted nice.',
    subhead: 'Loyalty + contact cards for cafés.',
    caption: 'Regulars come back for the coffee — and the punch card in their wallet. Warm kraft stock, your logo, repeat visits.',
    cta: 'Café card sets',
    hashtags: ['coffeeshop', 'cafe', 'loyaltycard', 'smallbusiness', 'coffeelover', 'branding'],
    visualDirection: '따뜻한 카페 톤, 크라프트 펀치카드 + 라떼. 손이 카드를 건네는 컷, 우드 테이블.',
  },
  {
    id: 'IG-19',
    slug: 'usecase-beauty-tattoo',
    productSlug: 'premium-foil-cards',
    productLabel: 'Foil Cards',
    category: 'cards',
    format: 'single',
    ratio: '4:5',
    theme: 'goldFoil',
    headline: 'Booked out?\nLook the part.',
    subhead: 'Foil cards for salons, tattoo & beauty.',
    caption: 'Your work is art — your card should match. Black stock, gold foil, a QR straight to your booking page.',
    cta: 'Beauty & tattoo cards',
    hashtags: ['tattooartist', 'hairstylist', 'nailtech', 'beautysalon', 'businesscards', 'foilcards'],
    visualDirection: '다크 무드, 금박 카드 + 부킹 QR, 살롱/타투 스튜디오 배경 보케.',
  },
  {
    id: 'IG-20',
    slug: 'usecase-wedding',
    productSlug: 'wedding-cards',
    productLabel: 'Wedding Suite',
    category: 'marketing',
    format: 'carousel',
    ratio: '4:5',
    theme: 'wedding',
    headline: 'One suite,\nevery detail',
    subhead: 'Invites, thank-yous & place cards →',
    caption: 'From save-the-dates to thank-you cards — one cohesive suite, one calm checkout. Pearl, foil, or letterpress.',
    cta: 'Wedding suite',
    hashtags: ['weddinginvitations', 'weddingstationery', 'weddingplanning', 'letterpress', 'foil', 'bridetobe'],
    visualDirection: '소프트 화이트/블러시 톤, 청첩장+땡큐카드+플레이스카드 세트 플랫레이, 유칼립투스. 펄/금박 디테일.',
    slides: [
      { title: 'One suite, every detail', text: 'Cohesive wedding stationery, start to finish. Swipe →' },
      { title: 'Invitations', text: 'Pearl, foil, or letterpress on luxe cotton stock.' },
      { title: 'Thank-you cards', text: 'Match the invite, finish the story.' },
      { title: 'Place & menu cards', text: 'Tie the whole table together.' },
    ],
  },
  {
    id: 'IG-21',
    slug: 'usecase-restaurant-menu',
    productSlug: 'menus',
    productLabel: 'Menus & Loyalty',
    category: 'marketing',
    format: 'single',
    ratio: '4:5',
    theme: 'amber',
    headline: 'Menus that\nmake people\norder more',
    subhead: 'Print menus, loyalty cards & table cards.',
    caption: 'A clean, durable menu does quiet selling all night. Pair it with a loyalty card and watch tables come back.',
    cta: 'Restaurant prints',
    hashtags: ['restaurant', 'menudesign', 'foodbusiness', 'hospitality', 'smallbusiness', 'print'],
    visualDirection: '따뜻한 레스토랑 조명, 인쇄 메뉴 + 로열티 카드 테이블 세팅. 음식 보케.',
  },
  {
    id: 'IG-22',
    slug: 'usecase-startup',
    productSlug: 'metallic-business-cards',
    productLabel: 'Metallic Cards',
    category: 'cards',
    format: 'single',
    ratio: '1:1',
    theme: 'metallic',
    headline: 'Series A energy,\nseed-round\nbudget',
    subhead: 'Metallic cards for founders.',
    caption: 'Walk into the room looking funded. Metallic stock, sharp logo, QR to your deck. First impressions compound.',
    cta: 'Founder cards',
    hashtags: ['startup', 'founder', 'techstartup', 'businesscards', 'networking', 'branding'],
    visualDirection: '모던 테크 톤, 메탈릭 카드 + 노트북/배지. 컨퍼런스 네트워킹 보케.',
  },
  {
    id: 'IG-23',
    slug: 'usecase-photographer',
    productSlug: 'premium-business-cards',
    productLabel: 'Premium Cards',
    category: 'cards',
    format: 'single',
    ratio: '4:5',
    theme: 'studio',
    headline: 'Let your work\ndo the talking',
    subhead: 'Photo-finish cards for creatives.',
    caption: 'Your portfolio is the pitch. A soft-touch card with one stunning frame on the back keeps you in mind long after the shoot.',
    cta: 'Creative cards',
    hashtags: ['photographer', 'creativebusiness', 'freelancer', 'businesscards', 'portfolio', 'branding'],
    visualDirection: '미니멀 스튜디오, 카드 뒷면에 풀블리드 사진, 소프트터치 매트. 카메라 옆 플랫레이.',
  },
  {
    id: 'IG-24',
    slug: 'usecase-event-planner',
    productSlug: 'postcards',
    productLabel: 'Postcards & Invites',
    category: 'marketing',
    format: 'single',
    ratio: '4:5',
    theme: 'amber',
    headline: 'Set the tone\nbefore they\narrive',
    subhead: 'Invites & postcards for events.',
    caption: 'The invite is the first scene of your event. Heavy stock, foil accents, a QR to RSVP — anticipation, printed.',
    cta: 'Event invites',
    hashtags: ['eventplanner', 'eventplanning', 'invitations', 'postcards', 'partyplanner', 'print'],
    visualDirection: '이벤트 톤, 금박 액센트 초대장 + RSVP QR, 플랫레이. 페스티브 보케.',
  },

  // --- D. 오퍼/브랜드/신뢰 (6) ---
  {
    id: 'IG-25',
    slug: 'brand-free-design-help',
    productSlug: 'business-cards',
    productLabel: 'Business Cards',
    category: 'brand',
    format: 'single',
    ratio: '1:1',
    theme: 'studio',
    headline: 'No design file?\nWe\'ll lay it\nout for you',
    subhead: 'Free design help before you pay.',
    caption: 'Send us your logo and a few details. We\'ll set up your card and send a proof — no charge, no commitment.',
    cta: 'Get free design help',
    hashtags: ['businesscards', 'smallbusiness', 'designhelp', 'branding', 'startup', 'print'],
    visualDirection: '친근한 톤, 로고 업로드 → 완성 카드 변환 시각화. 손이 핸드폰으로 로고 보내는 컷.',
  },
  {
    id: 'IG-26',
    slug: 'brand-worldwide-shipping',
    productSlug: 'business-cards',
    productLabel: 'Business Cards',
    category: 'brand',
    format: 'single',
    ratio: '4:5',
    theme: 'navy',
    headline: 'Printed global.\nDelivered\nto your door.',
    subhead: 'FedEx Express, worldwide.',
    caption: 'Produced at certified print facilities, shipped door-to-door via FedEx Express. Wherever you are, your cards arrive ready.',
    cta: 'See shipping',
    hashtags: ['worldwideshipping', 'businesscards', 'fedex', 'printondemand', 'smallbusiness', 'global'],
    visualDirection: '지구본/항공 모티프 + FedEx 박스 + 카드, 클린 네이비. 배송 동선 일러스트.',
  },
  {
    id: 'IG-27',
    slug: 'brand-firm-price',
    productSlug: 'business-cards',
    productLabel: 'Business Cards',
    category: 'brand',
    format: 'single',
    ratio: '1:1',
    theme: 'amber',
    headline: 'Upload.\nSee the price.\nThen pay.',
    subhead: 'A firm quote before checkout — no surprises.',
    caption: 'No "request a quote" runaround. Upload your file, choose options, see a firm price up front. Then decide.',
    cta: 'Get your price',
    hashtags: ['businesscards', 'transparentpricing', 'smallbusiness', 'printondemand', 'nosurprises', 'branding'],
    visualDirection: '업로드→가격→결제 3스텝 UI 목업, 클린 앰버. 손가락 탭 모션.',
  },
  {
    id: 'IG-28',
    slug: 'brand-reprint-guarantee',
    productSlug: 'business-cards',
    productLabel: 'Business Cards',
    category: 'brand',
    format: 'single',
    ratio: '4:5',
    theme: 'navy',
    headline: 'Not right?\nWe reprint\nor refund.',
    subhead: 'Our quality guarantee.',
    caption: 'If your order doesn\'t meet our quality standards, we reprint or refund — simple as that. Order with confidence.',
    cta: 'Read the guarantee',
    hashtags: ['qualityguarantee', 'businesscards', 'smallbusiness', 'customerfirst', 'printondemand', 'trust'],
    visualDirection: '신뢰 톤, 체크 배지 + 카드. 깔끔한 네이비, 보증 아이콘.',
  },
  {
    id: 'IG-29',
    slug: 'brand-behind-the-scenes',
    productSlug: 'premium-business-cards',
    productLabel: 'Premium Cards',
    category: 'brand',
    format: 'carousel',
    ratio: '4:5',
    theme: 'mono',
    headline: 'How your card\nis actually\nmade',
    subhead: 'A peek inside the press →',
    caption: 'From file to foil. A quick look at how a premium card goes from your upload to your hand.',
    cta: 'See the process',
    hashtags: ['printing', 'behindthescenes', 'foilstamping', 'businesscards', 'craftsmanship', 'print'],
    visualDirection: '인쇄 공정 BTS(프루핑→인쇄→박→재단→검수) 4컷, 다큐 톤 흑백+포인트.',
    slides: [
      { title: 'How your card is made', text: 'From your file to your hand. Swipe →' },
      { title: 'Proof', text: 'We set up your file and confirm before anything prints.' },
      { title: 'Press & finish', text: 'Offset print, then foil / letterpress / spot-UV.' },
      { title: 'Cut & check', text: 'Precision cut, hand-inspected, FedEx to your door.' },
    ],
  },
  {
    id: 'IG-30',
    slug: 'brand-new-year-refresh',
    productSlug: 'business-cards',
    productLabel: 'Business Cards',
    category: 'brand',
    format: 'single',
    ratio: '1:1',
    theme: 'goldFoil',
    headline: 'New season.\nNew card.',
    subhead: 'Refresh your brand before the next handshake.',
    caption: 'New role, new logo, new energy? Let your card catch up. A fresh design lands before your next meeting.',
    cta: 'Refresh my card',
    hashtags: ['newbeginnings', 'businesscards', 'rebrand', 'smallbusiness', 'branding', 'networking'],
    visualDirection: '시즌 리프레시 톤, 헌 카드→새 카드 전환. 금박 포인트, 캘린더/새출발 모티프.',
  },
]

// ---------------------------------------------------------------------------
// OMO-3690 · 생성 이미지 머지. scripts/omo3690-gen.mjs 가 /api/studio/gen 으로 생성한
// Supabase Storage public URL 을 studio-generated.json 에 적재 → 해당 IG 항목 imageUrl 채움.
// 비어있는 항목은 기존 CSS 컨셉 목업 폴백(무손상). 생성 성공분만 실이미지로 교체된다.
// ---------------------------------------------------------------------------
export const INSTAGRAM_POSTS: InstagramPost[] = RAW_INSTAGRAM_POSTS.map((p) => {
  const url = (GENERATED_IMAGES as Record<string, string>)[p.id]
  return url ? { ...p, imageUrl: url } : p
})

// 생성된 실이미지 보유 IG id 수(스튜디오 헤더 통계용).
export const GENERATED_IMAGE_COUNT = Object.keys(GENERATED_IMAGES).length

// Supabase Storage 공개 버킷명(이미지 프로덕션 산출물). 라우트/스크립트와 동일해야 함.
export const STUDIO_IMAGE_BUCKET = 'studio-ads'

// OMO-3690 · 이미지 생성 프롬프트 빌더. visualDirection(SSOT) + 제품/비율/컴플라이언스 가드를
// 묶어 photorealistic 제품샷 프롬프트로 변환. 텍스트/로고/스탯 합성 금지(OMO-2760/2975).
export function buildImagePrompt(post: InstagramPost): string {
  const ratioHint =
    post.ratio === '1:1'
      ? 'square 1:1 composition'
      : post.ratio === '9:16'
        ? 'tall vertical 9:16 composition'
        : 'vertical 4:5 portrait composition'
  return [
    `Ultra-realistic commercial product photography of a ${post.productLabel.toLowerCase()} for a premium American print shop.`,
    `Scene direction: ${post.visualDirection}`,
    `Beautiful styled background, soft directional studio lighting, shallow depth of field, true-to-life paper texture and print finish, crisp macro detail, magazine-quality, modern and elegant.`,
    `IMPORTANT: the product surface is blank or shows only abstract non-readable decorative marks. Absolutely no real text, no readable words, no letters, no numbers, no logos, no brand names, no statistics, no phone numbers, no QR codes.`,
    `${ratioHint}. No watermark, no border, no UI, photoreal only.`,
  ].join(' ')
}

// ---------------------------------------------------------------------------
// 메타(페이스북/인스타) 광고 30세트 — META_ADS 표준(OMO-3444) 적용
// 신규 테스트는 1캠페인-1광고세트-1광고. 검증 후 1캠페인-1광고세트-다광고로 스케일.
// 1차 지표 = CTR + ROI. 테스트 예산 = CAC(마진)×3~5.
// ---------------------------------------------------------------------------
const CAC = 'Set test budget at CAC(margin) × 3–5 (META_ADS 표준). 전환 확인 후 ON/OFF.'

export const META_AD_SETS: MetaAdSet[] = [
  // --- A. 프리미엄 카드, 트래픽 (5) ---
  {
    id: 'AD-01',
    campaign: 'PC | Foil Cards | Traffic',
    adsetName: 'Creatives & small biz · US',
    adName: 'Procard_IG_foil_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 25–55, small business owners, designers, creatives. Interests: branding, graphic design, entrepreneurship.',
    placements: 'IG Feed + Stories, FB Feed (Advantage+ placements)',
    primaryText: 'Real metallic foil — not printed gold. Hand one over and watch them look twice. Premium foil business cards, shipped worldwide.',
    headline: 'Foil cards that actually shine',
    description: 'Firm price before you pay. FedEx worldwide.',
    ctaButton: 'Shop Now',
    destination: 'premium-foil-cards',
    creativeRef: 'IG-01',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-02',
    campaign: 'PC | Letterpress | Traffic',
    adsetName: 'Design-led brands · US',
    adName: 'Procard_IG_letterpress_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 28–55, designers, boutique brand owners, stationery lovers. Interests: letterpress, branding, typography.',
    placements: 'IG Feed + Stories, FB Feed',
    primaryText: 'Some cards you see. Letterpress you feel — a deep press into thick cotton stock. The detail that says your brand cares.',
    headline: 'You can feel the quality',
    description: 'Cotton stock. Deep impression. Worldwide.',
    ctaButton: 'Learn More',
    destination: 'letterpress-business-cards',
    creativeRef: 'IG-02',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-03',
    campaign: 'PC | Transparent | Traffic',
    adsetName: 'Modern brands · US',
    adName: 'Procard_IG_transparent_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 22–45, startups, modern service brands, networkers. Interests: design, innovation, networking.',
    placements: 'IG Feed + Reels, FB Feed',
    primaryText: 'Hand someone a clear card and it never ends up in the bin. Frosted transparent plastic, sharp print, premium feel.',
    headline: 'See-through. Unforgettable.',
    description: 'Frosted plastic cards. Stand out.',
    ctaButton: 'Shop Now',
    destination: 'transparent-business-cards',
    creativeRef: 'IG-03',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-04',
    campaign: 'PC | Pearl Cards | Traffic',
    adsetName: 'Premium & events · US',
    adName: 'Procard_IG_pearl_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 25–55, premium service brands, event pros, consultants. Interests: luxury, weddings, branding.',
    placements: 'IG Feed + Stories',
    primaryText: 'Understated, not boring. Pearlescent stock gives a soft shimmer that reads "premium" the second it\'s in hand.',
    headline: 'A subtle pearl shimmer',
    description: 'Pearl stock. Quietly premium.',
    ctaButton: 'Learn More',
    destination: 'pearl-business-cards',
    creativeRef: 'IG-04',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-05',
    campaign: 'PC | Metallic | Traffic',
    adsetName: 'Founders & tech · US',
    adName: 'Procard_IG_metallic_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 24–45, startup founders, tech professionals. Interests: startups, venture, networking, design.',
    placements: 'IG Feed + Reels, FB Feed',
    primaryText: 'For brands that don\'t whisper. Metallic stock with a brushed sheen — looks engineered, feels expensive.',
    headline: 'Built like a statement',
    description: 'Metallic business cards. Modern sheen.',
    ctaButton: 'Shop Now',
    destination: 'metallic-business-cards',
    creativeRef: 'IG-05',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },

  // --- B. 유즈케이스 리드/트래픽 (6) ---
  {
    id: 'AD-06',
    campaign: 'PC | Realtor | Traffic',
    adsetName: 'Real estate · US',
    adName: 'Procard_IG_realtor_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 28–60, real estate agents & brokers. Interests: real estate, realtor, NAR, real estate marketing.',
    placements: 'IG Feed + Stories, FB Feed',
    primaryText: 'Buyers judge fast. A heavy, premium card with a QR to your listings says "I close." Make every handoff count.',
    headline: 'Your card is your first showing',
    description: 'Premium realtor cards, worldwide.',
    ctaButton: 'Shop Now',
    destination: 'premium-business-cards',
    creativeRef: 'IG-17',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-07',
    campaign: 'PC | Cafe Loyalty | Traffic',
    adsetName: 'Cafés & coffee · US',
    adName: 'Procard_IG_cafe_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 22–50, café & coffee shop owners, food & beverage SMBs. Interests: coffee shop, small business, hospitality.',
    placements: 'IG Feed + Stories',
    primaryText: 'Regulars come back for the coffee — and the punch card in their wallet. Warm kraft stock, your logo, repeat visits.',
    headline: 'Buy 9, get 1. Printed nice.',
    description: 'Loyalty + contact cards for cafés.',
    ctaButton: 'Shop Now',
    destination: 'business-cards',
    creativeRef: 'IG-18',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-08',
    campaign: 'PC | Beauty & Tattoo | Traffic',
    adsetName: 'Salons, tattoo, beauty · US',
    adName: 'Procard_IG_beauty_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 21–45, tattoo artists, hairstylists, nail techs, estheticians. Interests: beauty, tattoo, salon.',
    placements: 'IG Feed + Reels + Stories',
    primaryText: 'Your work is art — your card should match. Black stock, gold foil, a QR straight to your booking page.',
    headline: 'Booked out? Look the part.',
    description: 'Foil cards for beauty & tattoo pros.',
    ctaButton: 'Shop Now',
    destination: 'premium-foil-cards',
    creativeRef: 'IG-19',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-09',
    campaign: 'PC | Restaurant | Traffic',
    adsetName: 'Restaurants & hospitality · US',
    adName: 'Procard_IG_restaurant_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 25–55, restaurant & bar owners, hospitality SMBs. Interests: restaurant, food business, hospitality.',
    placements: 'IG Feed + Stories, FB Feed',
    primaryText: 'A clean, durable menu does quiet selling all night. Pair it with a loyalty card and watch tables come back.',
    headline: 'Menus that make people order more',
    description: 'Menus, loyalty & table cards.',
    ctaButton: 'Learn More',
    destination: 'menus',
    creativeRef: 'IG-21',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-10',
    campaign: 'PC | Photographers | Traffic',
    adsetName: 'Photographers & creatives · US',
    adName: 'Procard_IG_photographer_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 22–50, photographers, videographers, freelance creatives. Interests: photography, freelance, portfolio.',
    placements: 'IG Feed + Reels',
    primaryText: 'Your portfolio is the pitch. A soft-touch card with one stunning frame on the back keeps you in mind long after the shoot.',
    headline: 'Let your work do the talking',
    description: 'Photo-finish cards for creatives.',
    ctaButton: 'Shop Now',
    destination: 'premium-business-cards',
    creativeRef: 'IG-23',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-11',
    campaign: 'PC | Founders | Traffic',
    adsetName: 'Startup founders · US',
    adName: 'Procard_IG_startup_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 24–45, startup founders, indie hackers, tech operators. Interests: startups, SaaS, venture, networking.',
    placements: 'IG Feed + Reels, FB Feed',
    primaryText: 'Walk into the room looking funded. Metallic stock, sharp logo, QR to your deck. First impressions compound.',
    headline: 'Series A energy, seed-round budget',
    description: 'Founder cards that travel well.',
    ctaButton: 'Shop Now',
    destination: 'metallic-business-cards',
    creativeRef: 'IG-22',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },

  // --- C. 스티커 트래픽 (4) ---
  {
    id: 'AD-12',
    campaign: 'PC | Holographic Stickers | Traffic',
    adsetName: 'Online sellers & brands · US',
    adName: 'Procard_IG_holosticker_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 18–40, Etsy/Shopify sellers, indie brands, makers. Interests: Etsy, small business, packaging, stickers.',
    placements: 'IG Feed + Reels + Stories',
    primaryText: 'Slap one on a laptop, a bottle, a package — holographic shimmer that shifts color as it moves. People will ask where you got them.',
    headline: 'Rainbow on repeat',
    description: 'Holographic stickers, any quantity.',
    ctaButton: 'Shop Now',
    destination: 'holographic-stickers',
    creativeRef: 'IG-07',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-13',
    campaign: 'PC | Die-Cut Stickers | Traffic',
    adsetName: 'Makers & creators · US',
    adName: 'Procard_IG_diecut_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 18–40, content creators, makers, indie brands. Interests: stickers, illustration, small business.',
    placements: 'IG Feed + Reels',
    primaryText: 'Logo, mascot, lettering — if you can draw it, we can cut it. Clean die-cut edges, weatherproof finish.',
    headline: 'Any shape you can draw',
    description: 'Custom die-cut stickers.',
    ctaButton: 'Shop Now',
    destination: 'die-cut-stickers',
    creativeRef: 'IG-08',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-14',
    campaign: 'PC | Eco / Kraft Stickers | Traffic',
    adsetName: 'Artisan & eco brands · US',
    adName: 'Procard_IG_ecosticker_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 22–45, artisan food/craft brands, eco-conscious sellers. Interests: sustainability, handmade, packaging.',
    placements: 'IG Feed + Stories',
    primaryText: 'Natural, recyclable, on-brand. Kraft and eco stickers that look as good as your values.',
    headline: 'Stickers that match your values',
    description: 'Kraft & eco stickers.',
    ctaButton: 'Learn More',
    destination: 'eco-stickers',
    creativeRef: 'IG-16',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-15',
    campaign: 'PC | Roll Labels | Traffic',
    adsetName: 'Product brands & packaging · US',
    adName: 'Procard_IG_rolllabel_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 24–50, packaged-goods brands, candle/cosmetic/food makers. Interests: packaging, product branding, CPG.',
    placements: 'IG Feed + Stories, FB Feed',
    primaryText: 'Bottles, jars, boxes — labels that wrap clean and stick for good. Order the roll, apply, repeat.',
    headline: 'Labels your product deserves',
    description: 'Roll labels for product brands.',
    ctaButton: 'Shop Now',
    destination: 'roll-stickers',
    creativeRef: 'IG-16',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },

  // --- D. 포스트카드/웨딩 (3) ---
  {
    id: 'AD-16',
    campaign: 'PC | Wedding Suite | Traffic',
    adsetName: 'Brides & wedding · US',
    adName: 'Procard_IG_wedding_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 24–40, engaged, wedding planners. Interests: wedding planning, invitations, bride-to-be, stationery.',
    placements: 'IG Feed + Stories + Reels',
    primaryText: 'From save-the-dates to thank-you cards — one cohesive suite, one calm checkout. Pearl, foil, or letterpress.',
    headline: 'One suite, every detail',
    description: 'Wedding stationery, start to finish.',
    ctaButton: 'Learn More',
    destination: 'wedding-cards',
    creativeRef: 'IG-20',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-17',
    campaign: 'PC | Event Invites | Traffic',
    adsetName: 'Event planners · US',
    adName: 'Procard_IG_event_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 25–55, event & party planners, nonprofits, corporate events. Interests: event planning, invitations.',
    placements: 'IG Feed + Stories',
    primaryText: 'The invite is the first scene of your event. Heavy stock, foil accents, a QR to RSVP — anticipation, printed.',
    headline: 'Set the tone before they arrive',
    description: 'Invites & postcards for events.',
    ctaButton: 'Shop Now',
    destination: 'postcards',
    creativeRef: 'IG-24',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-18',
    campaign: 'PC | Postcard Marketing | Traffic',
    adsetName: 'Local service SMBs · US',
    adName: 'Procard_IG_postcard_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 28–55, local service businesses (dental, fitness, home services). Interests: local marketing, small business.',
    placements: 'FB Feed + IG Feed',
    primaryText: 'Direct mail still works when the postcard is good. Heavy stock, bold offer, a QR that tracks every scan.',
    headline: 'Postcards that get a callback',
    description: 'Marketing postcards, worldwide.',
    ctaButton: 'Learn More',
    destination: 'postcards',
    creativeRef: 'IG-24',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },

  // --- E. 오퍼/리드/전환 (4) ---
  {
    id: 'AD-19',
    campaign: 'PC | Free Design Help | Leads',
    adsetName: 'No-design SMBs · US',
    adName: 'Procard_IG_designhelp_v1',
    objective: 'OUTCOME_LEADS',
    audience: 'US, 25–55, new small business owners, solopreneurs. Interests: small business, startup, entrepreneurship.',
    placements: 'IG Feed + Stories, FB Feed (Instant Form)',
    primaryText: 'No design file? Send us your logo and a few details — we\'ll lay out your card and send a proof. No charge, no commitment.',
    headline: 'We\'ll design your card for free',
    description: 'Free proof before you pay.',
    ctaButton: 'Get Offer',
    destination: 'business-cards',
    creativeRef: 'IG-25',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-20',
    campaign: 'PC | Firm Price | Traffic',
    adsetName: 'Quote-shy buyers · US',
    adName: 'Procard_IG_firmprice_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'US, 25–55, SMB owners comparing print vendors. Interests: small business, printing, branding.',
    placements: 'IG Feed, FB Feed',
    primaryText: 'No "request a quote" runaround. Upload your file, choose options, see a firm price up front. Then decide.',
    headline: 'See your price before you pay',
    description: 'Firm pricing. No surprises.',
    ctaButton: 'Get Quote',
    destination: 'business-cards',
    creativeRef: 'IG-27',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-21',
    campaign: 'PC | Guarantee | Conversion',
    adsetName: 'First-time buyers · US',
    adName: 'Procard_IG_guarantee_v1',
    objective: 'OUTCOME_SALES',
    audience: 'US, 25–55, first-time print buyers, risk-averse SMBs. Interests: small business, e-commerce, branding.',
    placements: 'IG Feed + Stories, FB Feed (Advantage+ shopping)',
    primaryText: 'If your order doesn\'t meet our quality standards, we reprint or refund — simple as that. Order with confidence.',
    headline: 'Reprint or refund guarantee',
    description: 'Order with confidence.',
    ctaButton: 'Shop Now',
    destination: 'business-cards',
    creativeRef: 'IG-28',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-22',
    campaign: 'PC | Worldwide Shipping | Traffic',
    adsetName: 'International SMBs · Global-EN',
    adName: 'Procard_IG_shipping_v1',
    objective: 'OUTCOME_TRAFFIC',
    audience: 'English-speaking, 25–55, SMBs outside major print hubs (CA, AU, UK, GCC). Interests: small business, branding.',
    placements: 'IG Feed + Stories, FB Feed',
    primaryText: 'Produced at certified print facilities, shipped door-to-door via FedEx Express. Wherever you are, your cards arrive ready.',
    headline: 'Printed global. Delivered to your door.',
    description: 'FedEx Express worldwide.',
    ctaButton: 'Learn More',
    destination: 'business-cards',
    creativeRef: 'IG-26',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },

  // --- F. 카드뉴스 인게이지먼트 (4) ---
  {
    id: 'AD-23',
    campaign: 'PC | Card News: Cheap Mistakes | Engagement',
    adsetName: 'Broad SMB awareness · US',
    adName: 'Procard_IG_cn_mistakes_v1',
    objective: 'OUTCOME_ENGAGEMENT',
    audience: 'US, 22–55, broad small business + design interest (Advantage+ audience).',
    placements: 'IG Feed + Stories (carousel)',
    primaryText: 'Your card is a first impression in 90mm. Avoid these 5 and it instantly reads more premium. Which one are you guilty of?',
    headline: '5 things that make a card look cheap',
    description: 'Swipe for the fixes.',
    ctaButton: 'Learn More',
    destination: 'business-cards',
    creativeRef: 'IG-09',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-24',
    campaign: 'PC | Card News: Finishes | Engagement',
    adsetName: 'Design-curious SMB · US',
    adName: 'Procard_IG_cn_finishes_v1',
    objective: 'OUTCOME_ENGAGEMENT',
    audience: 'US, 22–55, small business + graphic design interests.',
    placements: 'IG Feed + Stories (carousel)',
    primaryText: 'Same design, three finishes, three completely different vibes. Here\'s how to choose the right one for your brand.',
    headline: 'Matte vs Gloss vs Soft-touch',
    description: 'Pick your finish.',
    ctaButton: 'Learn More',
    destination: 'premium-business-cards',
    creativeRef: 'IG-10',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-25',
    campaign: 'PC | Card News: 4 Steps | Engagement',
    adsetName: 'First-time designers · US',
    adName: 'Procard_IG_cn_4steps_v1',
    objective: 'OUTCOME_ENGAGEMENT',
    audience: 'US, 22–50, new SMBs, side-hustlers, no design background.',
    placements: 'IG Feed + Stories (carousel)',
    primaryText: 'You don\'t need design software. Four steps from logo to door. Save this for your next order.',
    headline: 'Design a card in 4 steps',
    description: 'No designer needed.',
    ctaButton: 'Learn More',
    destination: 'business-cards',
    creativeRef: 'IG-12',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },
  {
    id: 'AD-26',
    campaign: 'PC | Card News: Foil vs Letterpress | Engagement',
    adsetName: 'Premium-curious · US',
    adName: 'Procard_IG_cn_premium_v1',
    objective: 'OUTCOME_ENGAGEMENT',
    audience: 'US, 25–55, premium brand owners, designers.',
    placements: 'IG Feed + Stories (carousel)',
    primaryText: 'Three "premium" finishes people mix up. Here\'s what foil, letterpress, and embossing actually do — so you order the right one.',
    headline: 'Foil vs Letterpress vs Emboss',
    description: 'Know the difference.',
    ctaButton: 'Learn More',
    destination: 'premium-foil-cards',
    creativeRef: 'IG-14',
    primaryMetric: 'CTR + ROI',
    budgetRule: CAC,
    structure: '1c-1a-1ad (test)',
  },

  // --- G. 리타게팅/룩어라이크 스케일 (4) ---
  {
    id: 'AD-27',
    campaign: 'PC | Retarget Visitors | Conversion',
    adsetName: 'Site visitors 30d · US',
    adName: 'Procard_IG_rt_visitors_v1',
    objective: 'OUTCOME_SALES',
    audience: 'Retargeting: website visitors last 30 days, excluding purchasers. (Meta Pixel custom audience.)',
    placements: 'IG Feed + Stories, FB Feed (Advantage+ shopping)',
    primaryText: 'Still thinking it over? Your card is one upload away. Firm price before you pay, reprint-or-refund guaranteed.',
    headline: 'Finish your design',
    description: 'Firm price. Guaranteed quality.',
    ctaButton: 'Shop Now',
    destination: 'business-cards',
    creativeRef: 'IG-01',
    primaryMetric: 'CTR + ROI',
    budgetRule: 'Retargeting: warm audience, expect higher ROI. Scale via 1c-1a-multiad when CTR/ROI proven.',
    structure: '1c-1a-multiad (scale)',
  },
  {
    id: 'AD-28',
    campaign: 'PC | Retarget Cart | Conversion',
    adsetName: 'Add-to-cart 14d · US',
    adName: 'Procard_IG_rt_cart_v1',
    objective: 'OUTCOME_SALES',
    audience: 'Retargeting: add-to-cart / initiated-checkout last 14 days, no purchase. (Meta Pixel custom audience.)',
    placements: 'IG Feed + Stories, FB Feed',
    primaryText: 'Your cards are waiting. Complete your order and we\'ll get them on the press — FedEx to your door.',
    headline: 'Your cards are waiting',
    description: 'Complete your order.',
    ctaButton: 'Shop Now',
    destination: 'cart',
    creativeRef: 'IG-27',
    primaryMetric: 'CTR + ROI',
    budgetRule: 'Hottest audience. Highest expected ROI — fund first.',
    structure: '1c-1a-multiad (scale)',
  },
  {
    id: 'AD-29',
    campaign: 'PC | Lookalike Purchasers | Sales',
    adsetName: 'LAL 1–3% of purchasers · US',
    adName: 'Procard_IG_lal_purchasers_v1',
    objective: 'OUTCOME_SALES',
    audience: 'Lookalike 1–3% of past purchasers, US. (Built from Pixel purchase event.)',
    placements: 'IG Feed + Stories + Reels, FB Feed (Advantage+)',
    primaryText: 'Premium business cards that show up looking expensive — foil, letterpress, soft-touch. Firm price, worldwide shipping.',
    headline: 'Cards as good as your work',
    description: 'Premium finishes, worldwide.',
    ctaButton: 'Shop Now',
    destination: 'premium-business-cards',
    creativeRef: 'IG-06',
    primaryMetric: 'CTR + ROI',
    budgetRule: 'Scale winners here. Duplicate to scale only on big budget steps; +20%/week on existing for small steps (META_ADS).',
    structure: '1c-1a-multiad (scale)',
  },
  {
    id: 'AD-30',
    campaign: 'PC | Broad Creative Test | Sales',
    adsetName: 'Advantage+ broad · US',
    adName: 'Procard_IG_broad_v1',
    objective: 'OUTCOME_SALES',
    audience: 'US, broad (Advantage+ Shopping Campaign — minimal targeting, let the algorithm find buyers).',
    placements: 'All Advantage+ placements',
    primaryText: 'Hand over a card people actually keep. Premium stocks, real finishes, firm pricing, reprint-or-refund. Shipped worldwide.',
    headline: 'Business cards people keep',
    description: 'Premium print, worldwide.',
    ctaButton: 'Shop Now',
    destination: 'business-cards',
    creativeRef: 'IG-11',
    primaryMetric: 'CTR + ROI',
    budgetRule: 'ASC broad test. Once CTR/ROI clears, promote winning creative into 1c-1a-multiad set.',
    structure: '1c-1a-multiad (scale)',
  },
]

// 참고 레퍼런스(보드 지시: 핀터레스트/타사 인스타). 비주얼 디렉션 벤치마크용.
export const REFERENCE_BOARDS = [
  { label: 'Pinterest — "luxury business card foil"', note: '금박/레터프레스 매크로 라이팅, 다크 무드 플랫레이' },
  { label: 'Pinterest — "business card flat lay"', note: '소품(펜·커피·식물) 곁들인 데스크 스타일링 구도' },
  { label: 'Instagram — @moo (MOO)', note: '제품 매크로 + 클린 타이포, 핀치 컬러 배경' },
  { label: 'Instagram — @vistaprint', note: '유즈케이스/소상공인 스토리텔링, 캐러셀 팁' },
  { label: 'Instagram — @stickermule', note: '스티커 라이프스타일 적용 컷, 밝고 채도 높은 톤' },
  { label: 'Pinterest — "wedding stationery suite"', note: '청첩장 스위트 플랫레이, 유칼립투스/블러시' },
]
