-- OMO-3197: 성원 쇼핑백 4종 연동 — 라이브 재크롤 옵션 시드
-- 생성: scripts/omo3197-gen-migration.mjs ← scripts/omo3197-bag-options.json (2026-06-15)
-- 성원 상단 4버튼 = 4 category_code. DB 기존 옵션(100/200/500 등 임의값)을
-- 실측 성원 옵션(paper_code/paper_size/paper_qty)으로 교체한다.
--
-- ⚠️ 수량별 PRICING 은 미포함: 성원 쇼핑백 가격행렬은 index(unit_key) 기반이라
--    json_data 로 수량↔단가 매핑이 불가(calcuEstimate 인터랙티브 경로 필요).
--    → 신규 2종은 is_active=FALSE(드래프트), 가격 엔진은 후속 이슈에서 연동.
BEGIN;

-- ========== CPK4000 → paper-shopping-bags (종이끈 쇼핑백) ==========
DELETE FROM print_product_options WHERE product_id = (SELECT id FROM print_products WHERE slug='paper-shopping-bags')
  AND option_type IN ('paper','size','quantity','paper_code','paper_size','paper_qty','print_color_type');
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아트지 백색 180g', 'Art paper white 180g', 'ART180W00', 0, TRUE, 1 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아트지 백색 200g', 'Art paper white 200g', 'ART200W00', 0, FALSE, 2 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아트지 백색 250g', 'Art paper white 250g', 'ART250W00', 0, FALSE, 3 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '스노우지 백색 180g', 'Snow paper white 180g', 'SNW180W00', 0, FALSE, 4 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '스노우지 백색 200g', 'Snow paper white 200g', 'SNW200W00', 0, FALSE, 5 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '스노우지 백색 250g', 'Snow paper white 250g', 'SNW250W00', 0, FALSE, 6 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '랑데뷰 내츄럴 160g', 'Rendezvous natural 160g', 'RDV160N00', 0, FALSE, 7 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '랑데뷰 울트라화이트 160g', 'Rendezvous ultra-white 160g', 'RDV160UW0', 0, FALSE, 8 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아르떼 울트라화이트 160g', 'Arte ultra-white 160g', 'ARE160W00', 0, FALSE, 9 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '크린쇼핑백 화이트 140g', 'Clean bag stock white 140g', 'CSP140W01', 0, FALSE, 10 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '크린쇼핑백 화이트 160g', 'Clean bag stock white 160g', 'CSP160W01', 0, FALSE, 11 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '화이트140g', 'white140g', 'WHT140W00', 0, FALSE, 12 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '화이트160g', 'white160g', 'WHT160W00', 0, FALSE, 13 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '(친환경)비스포크쇼핑 백색 140g', '(eco) Bespoke eco bag white 140g', 'BSK140W00', 0, FALSE, 14 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '(친환경)비스포크쇼핑 백색 160g', '(eco) Bespoke eco bag white 160g', 'BSK160W00', 0, FALSE, 15 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '단면칼라', 'Color (1 side)', 'CTN10', 0, TRUE, 1 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '단면칼라+금색', 'Color + gold', 'CTN11', 0, FALSE, 2 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '단면칼라+은색', 'Color + silver', 'CTN12', 0, FALSE, 3 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '인쇄없음', 'No printing', 'CTN99', 0, FALSE, 4 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로180×높이200×폭100', '180 × 200 × 100 mm (W×H×D)', 'PK016', 0, TRUE, 1 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로210×높이300×폭85', '210 × 300 × 85 mm (W×H×D)', 'PK017', 0, FALSE, 2 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로265×높이250×폭105', '265 × 250 × 105 mm (W×H×D)', 'PK018', 0, FALSE, 3 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로270×높이380×폭100', '270 × 380 × 100 mm (W×H×D)', 'PK019', 0, FALSE, 4 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로300×높이400×폭130', '300 × 400 × 130 mm (W×H×D)', 'PK020', 0, FALSE, 5 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로310×높이230×폭100', '310 × 230 × 100 mm (W×H×D)', 'PK021', 0, FALSE, 6 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '직접입력', 'Custom size', 'PK098', 0, FALSE, 7 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '200매', '200 pcs', '200', 0, TRUE, 1 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '500매', '500 pcs', '500', 0, FALSE, 2 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '1000매', '1000 pcs', '1000', 0, FALSE, 3 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '2000매', '2000 pcs', '2000', 0, FALSE, 4 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '3000매', '3000 pcs', '3000', 0, FALSE, 5 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '5000매', '5000 pcs', '5000', 0, FALSE, 6 FROM print_products WHERE slug='paper-shopping-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '10000매', '10000 pcs', '10000', 0, FALSE, 7 FROM print_products WHERE slug='paper-shopping-bags';

-- ========== CPK2000 → gift-bags (리본&브레이드 쇼핑백) ==========
DELETE FROM print_product_options WHERE product_id = (SELECT id FROM print_products WHERE slug='gift-bags')
  AND option_type IN ('paper','size','quantity','paper_code','paper_size','paper_qty','print_color_type');
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아트지 백색 180g', 'Art paper white 180g', 'ART180W00', 0, TRUE, 1 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아트지 백색 200g', 'Art paper white 200g', 'ART200W00', 0, FALSE, 2 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아트지 백색 250g', 'Art paper white 250g', 'ART250W00', 0, FALSE, 3 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '스노우지 백색 180g', 'Snow paper white 180g', 'SNW180W00', 0, FALSE, 4 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '스노우지 백색 200g', 'Snow paper white 200g', 'SNW200W00', 0, FALSE, 5 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '스노우지 백색 250g', 'Snow paper white 250g', 'SNW250W00', 0, FALSE, 6 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '랑데뷰 내츄럴 160g', 'Rendezvous natural 160g', 'RDV160N00', 0, FALSE, 7 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '랑데뷰 울트라화이트 160g', 'Rendezvous ultra-white 160g', 'RDV160UW0', 0, FALSE, 8 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아르떼 울트라화이트 160g', 'Arte ultra-white 160g', 'ARE160W00', 0, FALSE, 9 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '크린쇼핑백 화이트 140g', 'Clean bag stock white 140g', 'CSP140W01', 0, FALSE, 10 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '크린쇼핑백 화이트 160g', 'Clean bag stock white 160g', 'CSP160W01', 0, FALSE, 11 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '화이트140g', 'white140g', 'WHT140W00', 0, FALSE, 12 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '화이트160g', 'white160g', 'WHT160W00', 0, FALSE, 13 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '(친환경)비스포크쇼핑 백색 140g', '(eco) Bespoke eco bag white 140g', 'BSK140W00', 0, FALSE, 14 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '(친환경)비스포크쇼핑 백색 160g', '(eco) Bespoke eco bag white 160g', 'BSK160W00', 0, FALSE, 15 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '단면칼라', 'Color (1 side)', 'CTN10', 0, TRUE, 1 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '단면칼라+금색', 'Color + gold', 'CTN11', 0, FALSE, 2 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '단면칼라+은색', 'Color + silver', 'CTN12', 0, FALSE, 3 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '전면 먹1도', 'Black 1-color (full)', 'BDD21', 0, FALSE, 4 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '인쇄없음', 'No printing', 'CTN99', 0, FALSE, 5 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로260×높이360×폭100', '260 × 360 × 100 mm (W×H×D)', 'PK001', 0, TRUE, 1 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로330×높이450×폭100', '330 × 450 × 100 mm (W×H×D)', 'PK002', 0, FALSE, 2 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로300×높이380×폭130', '300 × 380 × 130 mm (W×H×D)', 'PK003', 0, FALSE, 3 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로210×높이300×폭80', '210 × 300 × 80 mm (W×H×D)', 'PK004', 0, FALSE, 4 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로270×높이190×폭100', '270 × 190 × 100 mm (W×H×D)', 'PK005', 0, FALSE, 5 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로180×높이230×폭70', '180 × 230 × 70 mm (W×H×D)', 'PK006', 0, FALSE, 6 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로250×높이250×폭80', '250 × 250 × 80 mm (W×H×D)', 'PK007', 0, FALSE, 7 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로150×높이210×폭60', '150 × 210 × 60 mm (W×H×D)', 'PK008', 0, FALSE, 8 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '직접입력', 'Custom size', 'PK099', 0, FALSE, 9 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '200매', '200 pcs', '200', 0, TRUE, 1 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '500매', '500 pcs', '500', 0, FALSE, 2 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '1000매', '1000 pcs', '1000', 0, FALSE, 3 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '2000매', '2000 pcs', '2000', 0, FALSE, 4 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '3000매', '3000 pcs', '3000', 0, FALSE, 5 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '5000매', '5000 pcs', '5000', 0, FALSE, 6 FROM print_products WHERE slug='gift-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '10000매', '10000 pcs', '10000', 0, FALSE, 7 FROM print_products WHERE slug='gift-bags';

-- ========== CPK3000 → handleless-bags (끈없는 쇼핑백) ==========
INSERT INTO print_products (
  slug, name_ko, name_en, category, base_price_krw, margin_multiplier,
  sort_order, is_active, min_order_quantity, production_days_min, production_days_max, unit_weight_g
) VALUES (
  'handleless-bags', '끈없는 쇼핑백', 'Handleless Bags', 'paper_bags', 110000, 4,
  50, FALSE, 1, 2, 4, 70
) ON CONFLICT (slug) DO NOTHING;
DELETE FROM print_product_options WHERE product_id = (SELECT id FROM print_products WHERE slug='handleless-bags')
  AND option_type IN ('paper','size','quantity','paper_code','paper_size','paper_qty','print_color_type');
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아트지 백색 180g', 'Art paper white 180g', 'ART180W00', 0, TRUE, 1 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아트지 백색 200g', 'Art paper white 200g', 'ART200W00', 0, FALSE, 2 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아트지 백색 250g', 'Art paper white 250g', 'ART250W00', 0, FALSE, 3 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '스노우지 백색 180g', 'Snow paper white 180g', 'SNW180W00', 0, FALSE, 4 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '스노우지 백색 200g', 'Snow paper white 200g', 'SNW200W00', 0, FALSE, 5 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '스노우지 백색 250g', 'Snow paper white 250g', 'SNW250W00', 0, FALSE, 6 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '랑데뷰 내츄럴 160g', 'Rendezvous natural 160g', 'RDV160N00', 0, FALSE, 7 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '랑데뷰 울트라화이트 160g', 'Rendezvous ultra-white 160g', 'RDV160UW0', 0, FALSE, 8 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '아르떼 울트라화이트 160g', 'Arte ultra-white 160g', 'ARE160W00', 0, FALSE, 9 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '단면칼라', 'Color (1 side)', 'CTN10', 0, TRUE, 1 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '단면칼라+금색', 'Color + gold', 'CTN11', 0, FALSE, 2 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '단면칼라+은색', 'Color + silver', 'CTN12', 0, FALSE, 3 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '전면 먹1도', 'Black 1-color (full)', 'BDD21', 0, FALSE, 4 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '인쇄없음', 'No printing', 'CTN99', 0, FALSE, 5 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로200×높이300×폭90', '200 × 300 × 90 mm (W×H×D)', 'PK011', 0, TRUE, 1 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로250×높이250×폭90', '250 × 250 × 90 mm (W×H×D)', 'PK012', 0, FALSE, 2 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로270×높이400×폭100', '270 × 400 × 100 mm (W×H×D)', 'PK013', 0, FALSE, 3 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로300×높이420×폭100', '300 × 420 × 100 mm (W×H×D)', 'PK014', 0, FALSE, 4 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로330×높이450×폭120', '330 × 450 × 120 mm (W×H×D)', 'PK015', 0, FALSE, 5 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '200매', '200 pcs', '200', 0, TRUE, 1 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '500매', '500 pcs', '500', 0, FALSE, 2 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '1000매', '1000 pcs', '1000', 0, FALSE, 3 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '2000매', '2000 pcs', '2000', 0, FALSE, 4 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '3000매', '3000 pcs', '3000', 0, FALSE, 5 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '5000매', '5000 pcs', '5000', 0, FALSE, 6 FROM print_products WHERE slug='handleless-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '10000매', '10000 pcs', '10000', 0, FALSE, 7 FROM print_products WHERE slug='handleless-bags';

-- ========== CPK5000 → small-batch-bags (소량 쇼핑백) ==========
INSERT INTO print_products (
  slug, name_ko, name_en, category, base_price_krw, margin_multiplier,
  sort_order, is_active, min_order_quantity, production_days_min, production_days_max, unit_weight_g
) VALUES (
  'small-batch-bags', '소량 쇼핑백', 'Small-Batch Bags', 'paper_bags', 64000, 4,
  50, FALSE, 1, 2, 4, 60
) ON CONFLICT (slug) DO NOTHING;
DELETE FROM print_product_options WHERE product_id = (SELECT id FROM print_products WHERE slug='small-batch-bags')
  AND option_type IN ('paper','size','quantity','paper_code','paper_size','paper_qty','print_color_type');
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_code', '화이트160g', 'white160g', 'WHT160W00', 0, TRUE, 1 FROM print_products WHERE slug='small-batch-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '단면칼라', 'Color (1 side)', 'CTN10', 0, TRUE, 1 FROM print_products WHERE slug='small-batch-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'print_color_type', '인쇄없음', 'No printing', 'CTN99', 0, FALSE, 2 FROM print_products WHERE slug='small-batch-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로180×높이200×폭100', '180 × 200 × 100 mm (W×H×D)', 'PK016', 0, TRUE, 1 FROM print_products WHERE slug='small-batch-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로210×높이300×폭85', '210 × 300 × 85 mm (W×H×D)', 'PK017', 0, FALSE, 2 FROM print_products WHERE slug='small-batch-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로260×높이250×폭90', '260 × 250 × 90 mm (W×H×D)', 'PK022', 0, FALSE, 3 FROM print_products WHERE slug='small-batch-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로225×높이270×폭105', '225 × 270 × 105 mm (W×H×D)', 'PK023', 0, FALSE, 4 FROM print_products WHERE slug='small-batch-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로260×높이370×폭90', '260 × 370 × 90 mm (W×H×D)', 'PK024', 0, FALSE, 5 FROM print_products WHERE slug='small-batch-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '가로150×높이150×폭80', '150 × 150 × 80 mm (W×H×D)', 'PK025', 0, FALSE, 6 FROM print_products WHERE slug='small-batch-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_size', '직접입력', 'Custom size', 'PK098', 0, FALSE, 7 FROM print_products WHERE slug='small-batch-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '50매', '50 pcs', '50', 0, TRUE, 1 FROM print_products WHERE slug='small-batch-bags';
INSERT INTO print_product_options (product_id, option_type, label_ko, label_en, value, extra_price_krw, is_default, sort_order) SELECT id, 'paper_qty', '100매', '100 pcs', '100', 0, FALSE, 2 FROM print_products WHERE slug='small-batch-bags';

COMMIT;
